Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,5 +20,7 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
         run: |
-          echo "::error::Jira Issue Status is empty!"
-          exit 1
+          if [ 1 -eq 1 ]; then
+            echo "::error::Jira Issue Status is empty!"
+            exit 1
+          fi
